"""update_table_id

Revision ID: d2bc818a998c
Revises: e226ff5a7d0c
Create Date: 2025-04-10 22:45:34.154936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2bc818a998c'
down_revision: Union[str, None] = 'e226ff5a7d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reservations_table_id'), 'reservations', ['table_id'], unique=False)
    op.drop_constraint('reservations_table_id_fkey', 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'tables', ['table_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key('reservations_table_id_fkey', 'reservations', 'tables', ['table_id'], ['id'])
    op.drop_index(op.f('ix_reservations_table_id'), table_name='reservations')
    # ### end Alembic commands ###
